name: reviewdog

on:
  pull_request:
    branches:
      - develop

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2.34'
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: install phpstan and psalm
        run: composer require phpstan/phpstan vimeo/psalm
      - name: run phpstan and reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./vendor/bin/phpstan analyse --error-format=raw --no-progress | reviewdog -reporter=github-pr-review -f=phpstan
      - name: Run reviewdog with psalm
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./vendor/bin/psalm --output-format=text | reviewdog -reporter=github-pr-review -f=psalm
